name: outside
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Navigation and Routes
  page_transition: ^2.0.2
  fluro: ^2.0.3

  # Requests
  dio: ^4.0.0

  # Animations
  lottie: ^1.1.0
  skeleton_loader: ^2.0.0+4

dev_dependencies:
  # app basic configs
  change_app_package_name: ^1.0.0 # flutter pub run change_app_package_name:main com.example.name
  flutter_native_splash: ^1.2.1 # flutter pub run flutter_native_splash:create
  flutter_launcher_icons: ^0.9.2 # flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons.yalm
  flutter_app_name: ^0.1.1 # flutter pub run flutter_app_name
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_app_name:
  name: "Pietro Boilerplate" # flutter pub run flutter_app_name

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/

